spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jbxx?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root

server:
  port: 8090


# sql日志和参数 打印到控制台
mybatis-plus:
  configuration:
    log-impl:
      - org.apache.ibatis.logging.stdout.StdOutImpl
      - org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com:
      baomidou:
        mybatisplus: DEBUG
      example:
        demo:
          mapper: DEBUG  # 项目mapper目录


